name: MOHID_Postprocessing_environment
channels:
  - conda-forge
  - defaults
dependencies:
  - cartopy
  - dash
  - folium
  - geoglows
  - h5py
  - imageio-ffmpeg
  - ipyleaflet
  - ipywidgets
  - matplotlib
  - netcdf4
  - notebook
  - numpy
  - pandas
  - requests
  - scipy
  - tqdm
  - xarray
  - utide
  - rasterio
  - geopy
