name: MOHID_Preprocessing_environment
channels:
  - conda-forge
  - defaults
dependencies:
  - cartopy
  - geopandas
  - ipyleaflet
  - ipywidgets
  - matplotlib
  - notebook
  - numpy
  - pandas
  - pillow
  - pyogrio
  - pyshp
  - requests
  - scipy
  - shapely
  - fiona
